# .swiftlint.yml

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping

included:
  - Remy

excluded:
  - Remy.xcodeproj
  - .build

line_length:
  warning: 120
  error: 150

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length: 2
  max_length: 50
